version: "3.9"
services:
  web:
    build: ./ing_web
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - flesch_kinkaid_service
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/web
    networks:
      - default
  flesch_kinkaid_service:
    build: ./flesch_kinkaid_service
    ports:
      - "3001:3000"
    networks:
      - default
  postgres:
    image: "postgres:latest"
    ports:
      - "6231:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - default